Added special case logic for M1 macs.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -7,7 +7,9 @@ install_helm() {
   local install_type=$1
   local version=$2
   local install_path=$3
-  local platform="$(uname | tr '[:upper:]' '[:lower:]')-$(getArch)"
+  local operating_system="$(uname | tr '[:upper:]' '[:lower:]')"
+  local arch="$(getArch)"
+  local platform="$operating_system-$arch"
   local bin_install_path="$install_path/bin"
   local binary_path="$bin_install_path/helm"
   local download_url=$(get_download_url $version $platform)
@@ -19,6 +21,21 @@ install_helm() {
   fi
 
   local download_path="$tmp_download_dir/$(get_filename $version $platform)"
+
+  echo "Checking if download url ${download_url} is valid"
+  local http_status=$(curl -s -o /dev/null -I -w "%{http_code}" "$download_path")
+
+  if [[ "$http_status" != "200" ]] ; then
+    echo "Unable to download helm binary"
+    if [[ "$operating_system" == "darwin" ]] && [[ "$arch" == "arm64" ]] ; then
+      echo "M1 mac detected, couldn't find arm64 version, falling back to rosetta compatible amd64 version."
+      local platform="darwin-amd64"
+      local download_url=$(get_download_url $version $platform)
+    else
+      echo "Fast failing"
+      exit 1
+    fi
+  fi
 
   echo "Downloading helm from ${download_url} to ${download_path}"
   curl -Lo $download_path $download_url
